import React from 'react'

const settings = () => {
  return (
    <div
      style={{
        backgroundColor: 'white',
        borderRadius: '10px',
        padding: '20px',
        boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.1)',
      }}
    >
      <h2>Support</h2>
      <p>Phone Number: (111)-111-1111</p>
      <p>Email: service@healthyplate.com</p>
      <hr />
      <h2>Frequently Asked Questions:</h2>
      <p>
        <b>1. What is HealthyPlate?</b>
      </p>
      <p>
        HealthyPlate is a web application designed to assist college students in creating
        well-balanced meal plans for the week. It utilizes AI technology to generate personalized
        meal plans based on user interests and dietary preferences.
      </p>
      <p>
        <b>2. How does HealthyPlate Work?</b>
      </p>
      <p>
        Users start by entering their meal preferences and any allergies they may have. The
        AI-powered chatbot, Chat GPT, formulates a meal plan for the week based on this information.
        Users can further customize the plan through a text interface. The application also
        generates a grocery list based on the selected recipes.
      </p>
      <p>
        <b>3. What are the main features of HealthyPlate?</b>
      </p>
      <p>
        HealthyPlate offers several key features, including personalized meal planning, nutritional
        information display, cost estimation for the meal plan, and the ability to create a grocery
        list based on selected recipes.
      </p>
      <p>
        <b>4. What technologies are used to develop HealthyPlate?</b>
      </p>
      <p>
        HealthyPlate is developed using JavaScript with the React framework for a user-friendly
        interface. The data is stored and managed using MongoDB.
      </p>
      <p>
        <b>5. Can I edit the meal plan generated by HealthyPlate?</b>
      </p>
      <p>
        Absolutely! After the AI-generated meal plan is presented, you can easily edit and customize
        it according to your preferences and requirements through the text interface.
      </p>
      <p>
        <b>6. Does HealthyPlate track my nutritional intake?</b>
      </p>
      <p>
        Yes, HealthyPlate allows you to track your nutritional intake based on the meals in your
        plan. You can keep an eye on essential nutrients and ensure you&apos;re meeting your dietary
        goals.
      </p>
      <p>
        <b>7. Can I get a grocery list for the meal plan?</b>
      </p>
      <p>
        Definitely! HealthyPlate provides a grocery list feature that compiles all the required
        ingredients from the selected recipes in your meal plan.
      </p>
      <p>
        <b>8. Is HealthyPlate accessible on mobile devices?</b>
      </p>
      <p>
        While the primary focus is on desktop compatibility, we are considering mobile device
        support to provide a more versatile user experience.
      </p>
      <p>
        <b>9. What browsers are supported by HealthyPlate?</b>
      </p>
      <p>
        HealthyPlate is designed to be compatible with popular browsers like Chrome, Firefox,
        Safari, and Edge, ensuring accessibility for a wide range of users.
      </p>
      <p>
        <b>10. How secure is my data on HealthyPlate?</b>
      </p>
      <p>
        We take data security seriously. User log-in information and meal data are securely stored
        to protect your personal information.
      </p>
      <p>
        <b>11. Are ingredient prices and availability based in the United States only?</b>
      </p>
      <p>
        Yes, for now, HealthyPlate considers ingredient prices and availability within the United
        States.
      </p>
      <p>
        <b>12. Is there a cost to use HealthyPlate?</b>
      </p>
      <p>
        HealthyPlate is currently offered free of charge to help college students maintain a healthy
        and balanced diet.
      </p>
      <p>
        <b>13. Can I save my favorite recipes on HealthyPlate?</b>
      </p>
      <p>
        Yes, HealthyPlate allows you to save your favorite recipes, making it easy to access them
        for future meal planning.
      </p>
      <p>
        <b>14. Can I get support or assistance with using HealthyPlate?</b>
      </p>
      <p>
        Certainly! If you encounter any issues or have questions, feel free to reach out to our
        support team. We are here to assist you on your journey to healthier eating habits!
      </p>
    </div>
  )
}

export default settings
